export const CREATE_ROOM_NAME = "CREATE_ROOM_NAME";
export const SET_FULL_NAME = "SET_FULL_NAME";
export const SET_ADMIN_MESSAGE = "SET_ADMIN_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const SET_SHOW_MESSAGES = "SET_SHOW_MESSAGES";
export const SET_SHOW_USERS = "SET_SHOW_USERS";

